pip uninstall aldryn-newsblog==1.0.6
pip uninstall aldryn-people==1.0.1
pip uninstall aldryn-translation-tools==0.2.0
pip uninstall django-filer==0.9.12
pip uninstall django-grappelli==2.7.1
pip uninstall django-oscar==1.1.1
pip uninstall django-phonenumber-field==0.7.2
pip uninstall django-reversion==1.8.5
pip uninstall django-spurl==0.6.2
pip uninstall django-treebeard==3.0
pip uninstall djangocms-text-ckeditor==2.6.0
pip uninstall djangorestframework==3.2.4
pip uninstall icalendar==3.9.1
pip uninstall lxml==3.4.4
pip uninstall oauth2client==1.5.2
pip uninstall pexpect==3.3
pip uninstall phonenumbers==7.0.9
pip uninstall python-dateutil==2.4.2
pip uninstall python-slugify==1.1.4
pip uninstall requests==2.7.0
pip uninstall requests-oauthlib==0.5.0
pip uninstall shortuuid==0.4.2
pip uninstall simplejson==3.8.1
pip uninstall sqlparse==0.1.16
pip uninstall traitlets==4.0.0
pip uninstall tzlocal==1.2
pip uninstall Unidecode==0.4.18
pip uninstall urllib3==1.11
pip uninstall vobject==0.6.6
